CREATE SCHEMA IF NOT EXISTS market;
CREATE SCHEMA IF NOT EXISTS event;
CREATE SCHEMA IF NOT EXISTS economic;
CREATE SCHEMA IF NOT EXISTS news;
CREATE SCHEMA IF NOT EXISTS gpt;
CREATE SCHEMA IF NOT EXISTS factors;
CREATE SCHEMA IF NOT EXISTS fundamentals;
