"""Definitions and metadata for factor signals."""

from __future__ import annotations

from typing import Dict


FACTOR_DEFINITIONS: Dict[str, Dict[str, object]] = {
    "event.count_1d": {
        "description": "Number of events in the last 1 day; higher values imply more near-term uncertainty.",
        "direction": -1.0,
        "weight": -0.03,
        "source": "event",
        "window": 1,
        "normalization": "count",
    },
    "event.count_3d": {
        "description": "Number of events in the last 3 days; elevated counts signal short-term noise.",
        "direction": -1.0,
        "weight": -0.03,
        "source": "event",
        "window": 3,
        "normalization": "count",
    },
    "event.count_7d": {
        "description": "Number of events in the last 7 days; sustained activity can amplify risk.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 7,
        "normalization": "count",
    },
    "event.count_14d": {
        "description": "Number of events in the last 14 days; captures two-week catalyst density.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 14,
        "normalization": "count",
    },
    "event.count_30d": {
        "description": "Number of events in the last 30 days; broad measure of event pressure.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 30,
        "normalization": "count",
    },
    "event.count_60d": {
        "description": "Number of events in the last 60 days; persistent activity can indicate regime shifts.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 60,
        "normalization": "count",
    },
    "event.momentum_7d": {
        "description": "Change in event count vs prior 7-day window; rising momentum implies fresh shocks.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 7,
        "normalization": "delta",
    },
    "event.momentum_30d": {
        "description": "Change in event count vs prior 30-day window; rising counts imply persistent stress.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 30,
        "normalization": "delta",
    },
    "event.intensity_ratio_7d": {
        "description": "Share of 30-day events that occurred in the last 7 days; clustering raises risk.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 7,
    },
    "event.intensity_ratio_14d": {
        "description": "Share of 60-day events that occurred in the last 14 days; clustering raises risk.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 14,
    },
    "event.type_breadth_30d": {
        "description": "Distinct event types in the last 30 days; higher breadth implies cross-topic stress.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 30,
        "normalization": "count",
    },
    "event.type_breadth_90d": {
        "description": "Distinct event types in the last 90 days; broader shock mix tends to be bearish.",
        "direction": -1.0,
        "weight": -0.04,
        "source": "event",
        "window": 90,
        "normalization": "count",
    },
    "event.type_novelty_30d": {
        "description": "New event types in last 30 days not seen in prior months; novelty adds uncertainty.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 30,
        "normalization": "count",
    },
    "event.type_novelty_90d": {
        "description": "New event types in last 90 days vs prior year; novelty adds uncertainty.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 90,
        "normalization": "count",
    },
    "event.importance_high_7d": {
        "description": "Count of high-importance events in last 7 days; spikes are typically bearish.",
        "direction": -1.0,
        "weight": -0.06,
        "source": "event",
        "window": 7,
        "normalization": "count",
    },
    "event.importance_high_30d": {
        "description": "Count of high-importance events in last 30 days; sustained spikes imply risk.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 30,
        "normalization": "count",
    },
    "event.importance_ratio_7d": {
        "description": "Share of high-importance events in last 7 days; higher ratio implies heavier risk.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 7,
    },
    "event.importance_ratio_30d": {
        "description": "Share of high-importance events in last 30 days; higher ratio implies heavier risk.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "event",
        "window": 30,
    },
    "news.volume_3d": {
        "description": "Source-weighted articles in last 3 days (inverse source frequency).",
        "direction": 1.0,
        "weight": 0.03,
        "source": "news",
        "window": 3,
        "normalization": "count",
    },
    "news.volume_7d": {
        "description": "Source-weighted articles in last 7 days (inverse source frequency).",
        "direction": 1.0,
        "weight": 0.03,
        "source": "news",
        "window": 7,
        "normalization": "count",
    },
    "news.volume_14d": {
        "description": "Source-weighted articles in last 14 days (inverse source frequency).",
        "direction": 1.0,
        "weight": 0.02,
        "source": "news",
        "window": 14,
        "normalization": "count",
    },
    "news.volume_30d": {
        "description": "Source-weighted articles in last 30 days (inverse source frequency).",
        "direction": 1.0,
        "weight": 0.02,
        "source": "news",
        "window": 30,
        "normalization": "count",
    },
    "news.volume_momentum_7d": {
        "description": "Change in source-weighted volume vs prior 7 days.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "news",
        "window": 7,
        "normalization": "delta",
    },
    "news.volume_momentum_14d": {
        "description": "Change in source-weighted volume vs prior 14 days.",
        "direction": 1.0,
        "weight": 0.03,
        "source": "news",
        "window": 14,
        "normalization": "delta",
    },
    "news.sentiment_1d": {
        "description": "Average sentiment over 1 day; captures immediate tone.",
        "direction": 1.0,
        "weight": 0.08,
        "source": "news",
        "window": 1,
    },
    "news.sentiment_3d": {
        "description": "Average sentiment over 3 days; short-term tone.",
        "direction": 1.0,
        "weight": 0.1,
        "source": "news",
        "window": 3,
    },
    "news.sentiment_7d": {
        "description": "Average sentiment over 7 days; core tone signal.",
        "direction": 1.0,
        "weight": 0.15,
        "source": "news",
        "window": 7,
    },
    "news.sentiment_14d": {
        "description": "Average sentiment over 14 days; medium-term tone.",
        "direction": 1.0,
        "weight": 0.1,
        "source": "news",
        "window": 14,
    },
    "news.sentiment_30d": {
        "description": "Average sentiment over 30 days; long-term tone baseline.",
        "direction": 1.0,
        "weight": 0.08,
        "source": "news",
        "window": 30,
    },
    "news.sentiment_momentum_3d": {
        "description": "Short-term sentiment shift (3d vs 7d); rising tone is bullish.",
        "direction": 1.0,
        "weight": 0.12,
        "source": "news",
        "window": 3,
        "normalization": "delta",
        "scale": 0.2,
    },
    "news.sentiment_momentum_14d": {
        "description": "Medium-term sentiment shift (14d vs 30d); rising tone is bullish.",
        "direction": 1.0,
        "weight": 0.1,
        "source": "news",
        "window": 14,
        "normalization": "delta",
        "scale": 0.2,
    },
    "news.sentiment_dispersion_7d": {
        "description": "Dispersion of sentiment over 7 days; high dispersion implies uncertainty.",
        "direction": -1.0,
        "weight": -0.08,
        "source": "news",
        "window": 7,
    },
    "news.sentiment_dispersion_30d": {
        "description": "Dispersion of sentiment over 30 days; high dispersion implies uncertainty.",
        "direction": -1.0,
        "weight": -0.06,
        "source": "news",
        "window": 30,
    },
    "news.topic_volume_3d": {
        "description": "Count of topic mentions over 3 days; higher topic activity signals attention.",
        "direction": 1.0,
        "weight": 0.03,
        "source": "news",
        "window": 3,
        "normalization": "count",
    },
    "news.topic_volume_7d": {
        "description": "Count of topic mentions over 7 days; higher topic activity signals attention.",
        "direction": 1.0,
        "weight": 0.03,
        "source": "news",
        "window": 7,
        "normalization": "count",
    },
    "news.topic_velocity_3d": {
        "description": "Change in topic mentions over 3 days; rising topic velocity is bullish.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "news",
        "window": 3,
        "normalization": "delta",
    },
    "news.topic_velocity_7d": {
        "description": "Change in topic mentions over 7 days; rising topic velocity is bullish.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "news",
        "window": 7,
        "normalization": "delta",
    },
    "mkt.return_1d": {
        "description": "1-day return; positive returns support momentum.",
        "direction": 1.0,
        "weight": 0.02,
        "source": "market",
        "window": 1,
    },
    "mkt.return_5d": {
        "description": "5-day return; positive returns support momentum.",
        "direction": 1.0,
        "weight": 0.03,
        "source": "market",
        "window": 5,
    },
    "mkt.return_10d": {
        "description": "10-day return; positive returns support momentum.",
        "direction": 1.0,
        "weight": 0.03,
        "source": "market",
        "window": 10,
    },
    "mkt.return_20d": {
        "description": "20-day return; medium-term momentum signal.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "market",
        "window": 20,
    },
    "mkt.momentum_60d": {
        "description": "60-day momentum; sustained trend signal.",
        "direction": 1.0,
        "weight": 0.05,
        "source": "market",
        "window": 60,
    },
    "mkt.momentum_120d": {
        "description": "120-day momentum; longer-horizon trend signal.",
        "direction": 1.0,
        "weight": 0.05,
        "source": "market",
        "window": 120,
    },
    "mkt.sma_20_dist": {
        "description": "Distance from 20-day SMA; positive values imply short-term trend strength.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "market",
        "window": 20,
        "normalization": "self",
        "scale": 0.05,
    },
    "mkt.sma_50_dist": {
        "description": "Distance from 50-day SMA; gauges intermediate trend positioning.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "market",
        "window": 50,
        "normalization": "self",
        "scale": 0.08,
    },
    "mkt.sma_200_dist": {
        "description": "Distance from 200-day SMA; captures long-term trend regime.",
        "direction": 1.0,
        "weight": 0.05,
        "source": "market",
        "window": 200,
        "normalization": "self",
        "scale": 0.12,
    },
    "mkt.ma_cross_50_200": {
        "description": "50/200-day moving average spread; positive values imply trend support.",
        "direction": 1.0,
        "weight": 0.06,
        "source": "market",
        "window": 200,
        "normalization": "self",
        "scale": 0.08,
    },
    "mkt.drawdown_120d": {
        "description": "Drawdown from 120-day high; deeper drawdowns are bearish.",
        "direction": 1.0,
        "weight": 0.06,
        "source": "market",
        "window": 120,
        "normalization": "self",
        "scale": 0.1,
    },
    "mkt.breakout_252d": {
        "description": "Distance from 252-day high; values near zero imply breakout pressure.",
        "direction": 1.0,
        "weight": 0.06,
        "source": "market",
        "window": 252,
        "normalization": "self",
        "scale": 0.1,
    },
    "mkt.rsi_14": {
        "description": "RSI(14) minus 50; positive values indicate bullish momentum.",
        "direction": 1.0,
        "weight": 0.04,
        "source": "market",
        "window": 14,
        "normalization": "self",
        "scale": 15.0,
    },
    "mkt.vol_20d": {
        "description": "20-day volatility; higher volatility implies risk.",
        "direction": -1.0,
        "weight": -0.06,
        "source": "market",
        "window": 20,
    },
    "mkt.vol_60d": {
        "description": "60-day volatility; sustained volatility implies risk.",
        "direction": -1.0,
        "weight": -0.05,
        "source": "market",
        "window": 60,
    },
    "mkt.vol_z_20d": {
        "description": "20-day volatility vs 252-day baseline; spikes are bearish.",
        "direction": -1.0,
        "weight": -0.08,
        "source": "market",
        "window": 20,
    },
    "mkt.vol_z_60d": {
        "description": "60-day volatility vs 252-day baseline; spikes are bearish.",
        "direction": -1.0,
        "weight": -0.07,
        "source": "market",
        "window": 60,
    },
    "mkt.volume_z_20d": {
        "description": "20-day volume vs 252-day baseline; rising liquidity can be bullish.",
        "direction": 1.0,
        "weight": 0.03,
        "source": "market",
        "window": 20,
    },
    "mkt.volume_z_60d": {
        "description": "60-day volume vs 252-day baseline; sustained liquidity can be bullish.",
        "direction": 1.0,
        "weight": 0.02,
        "source": "market",
        "window": 60,
    },
}

MACRO_SERIES: Dict[str, Dict[str, object]] = {
    "VIXCLS": {
        "label": "VIX volatility index",
        "direction": -1.0,
        "weight": 0.05,
    },
    "DGS10": {
        "label": "10Y treasury yield",
        "direction": -1.0,
        "weight": 0.03,
    },
    "DGS2": {
        "label": "2Y treasury yield",
        "direction": -1.0,
        "weight": 0.03,
    },
    "T10Y2Y": {
        "label": "10Y-2Y yield curve",
        "direction": 1.0,
        "weight": 0.04,
    },
    "BAMLH0A0HYM2": {
        "label": "high yield credit spread",
        "direction": -1.0,
        "weight": 0.05,
    },
    "DCOILWTICO": {
        "label": "WTI crude oil",
        "direction": -1.0,
        "weight": 0.03,
    },
}

for series_id, meta in MACRO_SERIES.items():
    for window in (20, 60):
        FACTOR_DEFINITIONS[f"macro.{series_id}.z{window}"] = {
            "description": f"{meta['label']} z-score over {window} days; measures relative macro pressure.",
            "direction": meta["direction"],
            "weight": meta["weight"],
            "source": "economic",
            "window": window,
            "normalization": "self",
        }
        FACTOR_DEFINITIONS[f"macro.{series_id}.chg{window}"] = {
            "description": f"{meta['label']} change vs {window}-day average; gauges macro drift.",
            "direction": meta["direction"],
            "weight": meta["weight"],
            "source": "economic",
            "window": window,
            "normalization": "self",
        }


def get_factor_definitions() -> Dict[str, Dict[str, object]]:
    return FACTOR_DEFINITIONS
