"""PDF generation and email delivery for reports."""

import logging
import os
from datetime import datetime
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

import aiosmtplib
import markdown
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).parent / "templates"
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[2] / "output"


async def generate_pdf(sections: dict, output_path: Optional[str] = None, template_name: str = "report.html") -> str:
    """Generate PDF report from section data.

    Args:
        sections: Dict with report sections (what_happened, what_it_means, what_to_do, etc.)
        output_path: Optional output path. Defaults to output/market_report_{date}.pdf
        template_name: Jinja2 template file name.
    Returns:
        Path to generated PDF.
    """
    if output_path is None:
        DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        date_str = datetime.now().strftime("%Y-%m-%d")
        output_path = str(DEFAULT_OUTPUT_DIR / f"market_report_{date_str}.pdf")

    env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), autoescape=True)

    # Add markdown filter
    def md_to_html(text):
        if not text:
            return ""
        return markdown.markdown(text, extensions=["extra", "nl2br", "sane_lists"])

    env.filters["markdown"] = md_to_html

    template = env.get_template(template_name)
    html = template.render(
        date=datetime.now().strftime("%B %d, %Y"),
        time=datetime.now().strftime("%I:%M %p"),
        **sections,
    )
    HTML(string=html).write_pdf(output_path)
    size_kb = os.path.getsize(output_path) / 1024
    logger.info(f"PDF generated: {output_path} ({size_kb:.0f} KB)")
    return output_path


async def send_email(
    pdf_path: str,
    recipients: list[str],
    smtp_server: str = "smtp.gmail.com",
    smtp_port: int = 587,
    smtp_username: str = "",
    smtp_password: str = "",
    subject: Optional[str] = None,
) -> bool:
    """Send PDF report via email."""
    if not os.path.exists(pdf_path):
        logger.error(f"PDF not found: {pdf_path}")
        return False

    if not subject:
        subject = f"Tetra Market Report - {datetime.now().strftime('%Y-%m-%d')}"

    msg = MIMEMultipart()
    msg["From"] = smtp_username
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject

    body = f"""Daily Market Report - {datetime.now().strftime('%B %d, %Y')}

Your market intelligence report is attached.

---
Generated by Tetra
"""
    msg.attach(MIMEText(body, "plain"))

    with open(pdf_path, "rb") as f:
        att = MIMEApplication(f.read(), _subtype="pdf")
        att.add_header("Content-Disposition", "attachment", filename=Path(pdf_path).name)
        msg.attach(att)

    try:
        async with aiosmtplib.SMTP(
            hostname=smtp_server, port=smtp_port,
            username=smtp_username, password=smtp_password,
            start_tls=True,
        ) as smtp:
            await smtp.send_message(msg)
        logger.info(f"Report sent to {', '.join(recipients)}")
        return True
    except Exception as e:
        logger.error(f"Email failed: {e}")
        return False
